Window size - number of  of past values we are using  to predict  the  future value

<h3>Loading the libraries <h3>

In [32]:
import tensorflow as tf

In [33]:
dataset =tf.data.Dataset.range(10)  
#for val in dataset:
    #print(val)  
    # type of this val is tensor object, in our case it's scalar
    #print(val.numpy())
    # turning tensor object into numpy array

dataset=dataset.window(5,shift=1, drop_remainder=True)
# now this data  is a window dataset
# windowed dataset ->
'''[  Dataset([0, 1, 2, 3, 4]),
      Dataset([1, 2, 3, 4, 5]),
      Dataset([2, 3, 4, 5, 6]),
      Dataset([3, 4, 5, 6, 7]),
      Dataset([4, 5, 6, 7, 8]),
      Dataset([5, 6, 7, 8, 9])
]
'''
dataset = dataset.flat_map(lambda window: window.batch(5))
# here we are taking each window,
# batching  each windows elements into a tensor object
#Dataset[1,2,3,4,5] -> tensor flow object(1,2,3,4,5)
for val in dataset:
    print(val.numpy())
    #val.numpy() will turn the tensor flow object into numpy array
    





[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


2024-05-18 16:03:39.616210: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


<h3> Creating   the dataset <h3>

In [34]:
dataset = dataset.map(lambda window: (window[:-1],window[-1]))
for x, y in dataset:
    print(x.numpy(),y.numpy())
 # here we are mapping  window (type tensor object) element into a tuple of 
 #(first 4 elements of the window, last element of  the window)   

[0 1 2 3] 4
[1 2 3 4] 5
[2 3 4 5] 6
[3 4 5 6] 7
[4 5 6 7] 8
[5 6 7 8] 9


2024-05-18 16:03:39.646523: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


<h3> Shuffling <h3>


In [35]:
dataset =  dataset.shuffle(buffer_size=10)
for x, y in dataset:
    print(x.numpy(),y.numpy())


[1 2 3 4] 5
[4 5 6 7] 8
[2 3 4 5] 6
[3 4 5 6] 7
[0 1 2 3] 4
[5 6 7 8] 9


2024-05-18 16:03:39.670781: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


<h3> Batching <h3>

In [36]:
dataset= dataset.batch(2).prefetch(1)
for x,y in dataset:
    print("x="  , x.numpy())
    print("y=" ,y.numpy())

x= [[2 3 4 5]
 [1 2 3 4]]
y= [6 5]
x= [[3 4 5 6]
 [0 1 2 3]]
y= [7 4]
x= [[5 6 7 8]
 [4 5 6 7]]
y= [9 8]


2024-05-18 16:03:39.696823: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
